lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "annotated-types"
version = "0.7.0"

[[packages.wheels]]
name = "annotated_types-0.7.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v0.29.4/full/annotated_types-0.7.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "6a8e8a10986f2f73bf3aa1e63eb807c845bdf97a0fa436dfda1d4e8a81603fb0"

[[packages]]
name = "asttokens"
version = "3.0.1"

[[packages.wheels]]
name = "asttokens-3.0.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/d2/39/e7eaf1799466a4aef85b6a4fe7bd175ad2b1c6345066aa33f1f58d4b18d0/asttokens-3.0.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "15a3ebc0f43c2d0a50eeafea25e19046c68398e487b9f1f5b517f7c0f40f976a"

[[packages]]
name = "attrs"
version = "26.1.0"

[[packages.wheels]]
name = "attrs-26.1.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/64/b4/17d4b0b2a2dc85a6df63d1157e028ed19f90d4cd97c36717afef2bc2f395/attrs-26.1.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "c647aa4a12dfbad9333ca4e71fe62ddc36f4e63b2d260a37a8b83d2f043ac309"

[[packages]]
name = "dirty-equals"
version = "0.11"

[[packages.wheels]]
name = "dirty_equals-0.11-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/bb/8d/dbff05239043271dbeace563a7686212a3dd517864a35623fe4d4a64ca19/dirty_equals-0.11-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "b1d7093273fc2f9be12f443a8ead954ef6daaf6746fd42ef3a5616433ee85286"

[[packages]]
name = "dnspython"
version = "2.8.0"

[[packages.wheels]]
name = "dnspython-2.8.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ba/5a/18ad964b0086c6e62e2e7500f7edc89e3faa45033c71c1893d34eed2b2de/dnspython-2.8.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "01d9bbc4a2d76bf0db7c1f729812ded6d912bd318d3b1cf81d30c0f845dbf3af"

[[packages]]
name = "email-validator"
version = "2.3.0"

[[packages.wheels]]
name = "email_validator-2.3.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/de/15/545e2b6cf2e3be84bc1ed85613edd75b8aea69807a71c26f4ca6a9258e82/email_validator-2.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "80f13f623413e6b197ae73bb10bf4eb0908faf509ad8362c5edeb0be7fd450b4"

[[packages]]
name = "executing"
version = "2.2.1"

[[packages.wheels]]
name = "executing-2.2.1-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/c1/ea/53f2148663b321f21b5a606bd5f191517cf40b7072c0497d3c92c4a13b1e/executing-2.2.1-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "760643d3452b4d777d295bb167ccc74c64a81df23fb5e08eff250c425a4b2017"

[[packages]]
name = "faker"
version = "40.18.0"

[[packages.wheels]]
name = "faker-40.18.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/84/0b/5c0b2d3a4b7a715f1835dd3f963bfbe841a02ae5cad1df8ee0325dfad235/faker-40.18.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "61a6b94b74605ddb090a065deb197a1c585ae7a874c094cf6693671d271e6083"

[[packages]]
name = "hypothesis"
version = "6.152.7"

[[packages.wheels]]
name = "hypothesis-6.152.7-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/0a/1e/8222edaee03c37350eaa726213614e343a62f1e56396dd000ad9277bfa3d/hypothesis-6.152.7-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "c0b17dd428fcb6e962f60315f6f4a77816c72fbb281ce9ba73699dabead5ec82"

[[packages]]
name = "idna"
version = "3.15"

[[packages.wheels]]
name = "idna-3.15-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/d2/23/408243171aa9aaba178d3e2559159c24c1171a641aa83b67bdd3394ead8e/idna-3.15-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "048adeaf8c2d788c40fee287673ccaa74c24ffd8dcf09ffa555a2fbb59f10ac8"

[[packages]]
name = "iniconfig"
version = "2.3.0"

[[packages.wheels]]
name = "iniconfig-2.3.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/cb/b1/3846dd7f199d53cb17f49cba7e651e9ce294d8497c8c150530ed11865bb8/iniconfig-2.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "f631c04d2c48c52b84d0d0549c99ff3859c98df65b3101406327ecc7d53fbf12"

[[packages]]
name = "inline-snapshot"
version = "0.33.0"

[[packages.wheels]]
name = "inline_snapshot-0.33.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ce/2c/4b209e9dd6700cea0c0e39d7e5e70e9f494f817a374174a823bd11561d31/inline_snapshot-0.33.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "76b8c2c5899d27d3d464d1160eb3b8eee179ba635bb80a8e5e93220f10b60207"

[[packages]]
name = "jsonschema"
version = "4.26.0"

[[packages.wheels]]
name = "jsonschema-4.26.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/69/90/f63fb5873511e014207a475e2bb4e8b2e570d655b00ac19a9a0ca0a385ee/jsonschema-4.26.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "d489f15263b8d200f8387e64b4c3a75f06629559fb73deb8fdfb525f2dab50ce"

[[packages]]
name = "jsonschema-specifications"
version = "2025.9.1"

[[packages.wheels]]
name = "jsonschema_specifications-2025.9.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/41/45/1a4ed80516f02155c51f51e8cedb3c1902296743db0bbc66608a0db2814f/jsonschema_specifications-2025.9.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "98802fee3a11ee76ecaca44429fda8a41bff98b00a0f2838151b113f210cc6fe"

[[packages]]
name = "markdown-it-py"
version = "4.2.0"

[[packages.wheels]]
name = "markdown_it_py-4.2.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/b3/81/4da04ced5a082363ecfa159c010d200ecbd959ae410c10c0264a38cac0f5/markdown_it_py-4.2.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "9f7ebbcd14fe59494226453aed97c1070d83f8d24b6fc3a3bcf9a38092641c4a"

[[packages]]
name = "mdurl"
version = "0.1.2"

[[packages.wheels]]
name = "mdurl-0.1.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "84008a41e51615a49fc9966191ff91509e3c40b939176e643fd50a5c2196b8f8"

[[packages]]
name = "packaging"
version = "26.2"

[[packages.wheels]]
name = "packaging-26.2-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v0.29.4/full/packaging-26.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "7a0e80a4de677fefa2782ea4d34063708a3ac3d54469298f22cedcc4c7bebb4b"

[[packages]]
name = "pluggy"
version = "1.6.0"

[[packages.wheels]]
name = "pluggy-1.6.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/54/20/4d324d65cc6d9205fabedc306948156824eb9f0ee1633355a8f7ec5c66bf/pluggy-1.6.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "e920276dd6813095e9377c0bc5566d94c932c33b27a3e3945d8389c374dd4746"

[[packages]]
name = "py-cpuinfo"
version = "9.0.0"

[[packages.wheels]]
name = "py_cpuinfo-9.0.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/e0/a9/023730ba63db1e494a271cb018dcd361bd2c917ba7004c3e49d5daf795a2/py_cpuinfo-9.0.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "859625bc251f64e21f077d099d4162689c762b5d6a4c3c97553d56241c9674d5"

[[packages]]
name = "pygments"
version = "2.20.0"

[[packages.wheels]]
name = "pygments-2.20.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/f4/7e/a72dd26f3b0f4f2bf1dd8923c85f7ceb43172af56d63c7383eb62b332364/pygments-2.20.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "81a9e26dd42fd28a23a2d169d86d7ac03b46e2f8b59ed4698fb4785f946d0176"

[[packages]]
name = "pytest"
version = "9.0.3"

[[packages.wheels]]
name = "pytest-9.0.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/d4/24/a372aaf5c9b7208e7112038812994107bc65a84cd00e0354a88c2c77a617/pytest-9.0.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "2c5efc453d45394fdd706ade797c0a81091eccd1d6e4bccfcd476e2b8e0ab5d9"

[[packages]]
name = "pytest-benchmark"
version = "5.2.3"

[[packages.wheels]]
name = "pytest_benchmark-5.2.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/33/29/e756e715a48959f1c0045342088d7ca9762a2f509b945f362a316e9412b7/pytest_benchmark-5.2.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "bc839726ad20e99aaa0d11a127445457b4219bdb9e80a1afc4b51da7f96b0803"

[[packages]]
name = "pytest-mock"
version = "3.15.1"

[[packages.wheels]]
name = "pytest_mock-3.15.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/5a/cc/06253936f4a7fa2e0f48dfe6d851d9c56df896a9ab09ac019d70b760619c/pytest_mock-3.15.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "0a25e2eb88fe5168d535041d09a4529a188176ae608a6d249ee65abc0949630d"

[[packages]]
name = "pytest-pretty"
version = "1.3.0"

[[packages.wheels]]
name = "pytest_pretty-1.3.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ab/85/2f97a1b65178b0f11c9c77c35417a4cc5b99a80db90dad4734a129844ea5/pytest_pretty-1.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "074b9d5783cef9571494543de07e768a4dda92a3e85118d6c7458c67297159b7"

[[packages]]
name = "pytest-run-parallel"
version = "0.8.2"

[[packages.wheels]]
name = "pytest_run_parallel-0.8.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ae/ae/48c9c65807ecdfdd47abe8de308d805e2f3fd782838a0a54ed5505dae627/pytest_run_parallel-0.8.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "2a61aba89f56013859ca5c1efb660755bb6b0349ccfd1dbbef27a94b8c04fe4b"

[[packages]]
name = "python-dateutil"
version = "2.9.0.post0"

[[packages.wheels]]
name = "python_dateutil-2.9.0.post0-py2.py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v0.29.4/full/python_dateutil-2.9.0.post0-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "1fe3a0346ef21bc85b295227256d6aed72aa8116178b019fc5ae5d57fbd213cf"

[[packages]]
name = "pytz"
version = "2026.2"

[[packages.wheels]]
name = "pytz-2026.2-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ec/dd/96da98f892250475bdf2328112d7468abdd4acc7b902b6af23f4ed958ea0/pytz-2026.2-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "04156e608bee23d3792fd45c94ae47fae1036688e75032eea2e3bf0323d1f126"

[[packages]]
name = "referencing"
version = "0.37.0"

[[packages.wheels]]
name = "referencing-0.37.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/2c/58/ca301544e1fa93ed4f80d724bf5b194f6e4b945841c5bfd555878eea9fcb/referencing-0.37.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "381329a9f99628c9069361716891d34ad94af76e461dcb0335825aecc7692231"

[[packages]]
name = "rich"
version = "15.0.0"

[[packages.wheels]]
name = "rich-15.0.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/82/3b/64d4899d73f91ba49a8c18a8ff3f0ea8f1c1d75481760df8c68ef5235bf5/rich-15.0.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "33bd4ef74232fb73fe9279a257718407f169c09b78a87ad3d296f548e27de0bb"

[[packages]]
name = "rpds-py"
version = "0.30.0"

[[packages.wheels]]
name = "rpds_py-0.30.0-cp313-cp313-pyemscripten_2025_0_wasm32.whl"
url = "https://cdn.jsdelivr.net/pyodide/v0.29.4/full/rpds_py-0.30.0-cp313-cp313-pyemscripten_2025_0_wasm32.whl"

[packages.wheels.hashes]
sha256 = "ceaa03603678cc8550b7fc5c9d88b21bbd6d10523db19b5aeb22bb693f3896e7"

[[packages]]
name = "six"
version = "1.17.0"

[[packages.wheels]]
name = "six-1.17.0-py2.py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v0.29.4/full/six-1.17.0-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "bc830cfdc71a224b6d0e4337183a87ea53f21b6623deca5771ee3bc866fd8da2"

[[packages]]
name = "sortedcontainers"
version = "2.4.0"

[[packages.wheels]]
name = "sortedcontainers-2.4.0-py2.py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v0.29.4/full/sortedcontainers-2.4.0-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "6f0e86dfd7f1d707a1d9a398d0995ac6d30834e6a9a0530e2fb5ec02c1f6f05c"

[[packages]]
name = "typing-extensions"
version = "4.15.0"

[[packages.wheels]]
name = "typing_extensions-4.15.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v0.29.4/full/typing_extensions-4.15.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "42190f892f6219350c50e107954f57cb6196acac818fece4a7d21689c94f71de"

[[packages]]
name = "typing-inspection"
version = "0.4.2"

[[packages.wheels]]
name = "typing_inspection-0.4.2-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v0.29.4/full/typing_inspection-0.4.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "a00e8bbec6999ab79272b06aaacbeee737ff3c15cb8785b34fd189d35b0c24e0"

[[packages]]
name = "tzdata"
version = "2026.2"

[[packages.wheels]]
name = "tzdata-2026.2-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ce/e4/dccd7f47c4b64213ac01ef921a1337ee6e30e8c6466046018326977efd95/tzdata-2026.2-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "bbe9af844f658da81a5f95019480da3a89415801f6cc966806612cc7169bffe7"
