lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "annotated-types"
version = "0.7.0"

[[packages.wheels]]
name = "annotated_types-0.7.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/annotated_types-0.7.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "7beddfd593719e92d8d4d6c290a512ceff0f0879428417fced1384cf5417e8c4"

[[packages]]
name = "asttokens"
version = "3.0.1"

[[packages.wheels]]
name = "asttokens-3.0.1-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/asttokens-3.0.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "df85a646e630bb2649a22296eea308e3f3cf1cec104970eff772b4bf17dd7b31"

[[packages]]
name = "attrs"
version = "26.1.0"

[[packages.wheels]]
name = "attrs-26.1.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/attrs-26.1.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "b5f2e20d25fbeb55950af8cda6b5ef71d47e60872587d11ab6b6425b0d7c2c92"

[[packages]]
name = "dirty-equals"
version = "0.11"

[[packages.wheels]]
name = "dirty_equals-0.11-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/bb/8d/dbff05239043271dbeace563a7686212a3dd517864a35623fe4d4a64ca19/dirty_equals-0.11-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "b1d7093273fc2f9be12f443a8ead954ef6daaf6746fd42ef3a5616433ee85286"

[[packages]]
name = "dnspython"
version = "2.8.0"

[[packages.wheels]]
name = "dnspython-2.8.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/dnspython-2.8.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "087740d3b2bb9ac3ca01df6e09c03251e117600b32fda95e202dcd865859c213"

[[packages]]
name = "email-validator"
version = "2.3.0"

[[packages.wheels]]
name = "email_validator-2.3.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/de/15/545e2b6cf2e3be84bc1ed85613edd75b8aea69807a71c26f4ca6a9258e82/email_validator-2.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "80f13f623413e6b197ae73bb10bf4eb0908faf509ad8362c5edeb0be7fd450b4"

[[packages]]
name = "executing"
version = "2.2.1"

[[packages.wheels]]
name = "executing-2.2.1-py2.py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/executing-2.2.1-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "cc2c5f9bbd2cfc976c2827c3435c4d0ea013c7c6ed4bbbb33dfcc21ae376fd94"

[[packages]]
name = "faker"
version = "40.28.1"

[[packages.wheels]]
name = "faker-40.28.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/92/a6/6111b9f13c1564b0e2f5dbeeb611fd00dc731e6add2336f62b798598c73d/faker-40.28.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "e8d3f5c469100a553d246dce7937c291308068a5ec6c9c3a228d7878b50720be"

[[packages]]
name = "hypothesis"
version = "6.156.1"

[[packages.wheels]]
name = "hypothesis-6.156.1-cp314-cp314-pyemscripten_2026_0_wasm32.whl"
url = "https://files.pythonhosted.org/packages/1b/ca/dcd80b4606d97b5dba2775526aa89a7735086559c5a80eaf5bf60610bc10/hypothesis-6.156.1-cp314-cp314-pyemscripten_2026_0_wasm32.whl"

[packages.wheels.hashes]
sha256 = "209b76dab690e2182599a83c079475115d69dd2c16aed38a57bb9db376ba4195"

[[packages]]
name = "idna"
version = "3.18"

[[packages.wheels]]
name = "idna-3.18-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/1e/5e/d4e9f1a599fb8e573b7b87160658329fbf28d19eac2718f51fc3def3aa5a/idna-3.18-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "7f952cbe720b688055e3f87de14f5c3e5fdaa8bc3928985c4077ca689de849a2"

[[packages]]
name = "iniconfig"
version = "2.3.0"

[[packages.wheels]]
name = "iniconfig-2.3.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/iniconfig-2.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "1cd8448eea1c863c970703ed01fa1baf655043150cee772772253e3461b701ed"

[[packages]]
name = "inline-snapshot"
version = "0.34.2"

[[packages.wheels]]
name = "inline_snapshot-0.34.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/bb/2a/84fe7ef052ac666e95e7cabdf0905aa3f2c90b5a117419760b39b577602a/inline_snapshot-0.34.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "743a514a08ffd0d2d62878b0208d4def5041585affa7db6b89f0ca2e23552361"

[[packages]]
name = "jsonschema"
version = "4.26.0"

[[packages.wheels]]
name = "jsonschema-4.26.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/jsonschema-4.26.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "d2d29b9c8db3520b39feac084c913bbe79372f088ffb49fb59f44a1a7b57724a"

[[packages]]
name = "jsonschema-specifications"
version = "2025.9.1"

[[packages.wheels]]
name = "jsonschema_specifications-2025.9.1-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/jsonschema_specifications-2025.9.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "ad8df6243b990e76af93135ab36903225cdc03e1730fc433f93ac3934a50d05b"

[[packages]]
name = "markdown-it-py"
version = "4.2.0"

[[packages.wheels]]
name = "markdown_it_py-4.2.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/b3/81/4da04ced5a082363ecfa159c010d200ecbd959ae410c10c0264a38cac0f5/markdown_it_py-4.2.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "9f7ebbcd14fe59494226453aed97c1070d83f8d24b6fc3a3bcf9a38092641c4a"

[[packages]]
name = "mdurl"
version = "0.1.2"

[[packages.wheels]]
name = "mdurl-0.1.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "84008a41e51615a49fc9966191ff91509e3c40b939176e643fd50a5c2196b8f8"

[[packages]]
name = "packaging"
version = "26.2"

[[packages.wheels]]
name = "packaging-26.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/df/b2/87e62e8c3e2f4b32e5fe99e0b86d576da1312593b39f47d8ceef365e95ed/packaging-26.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "5fc45236b9446107ff2415ce77c807cee2862cb6fac22b8a73826d0693b0980e"

[[packages]]
name = "pluggy"
version = "1.6.0"

[[packages.wheels]]
name = "pluggy-1.6.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/pluggy-1.6.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "8358dcb4259589a6dbb54b42d0c437801bac4c69e843e617e3b529e9b7926fda"

[[packages]]
name = "py-cpuinfo"
version = "9.0.0"

[[packages.wheels]]
name = "py_cpuinfo-9.0.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/e0/a9/023730ba63db1e494a271cb018dcd361bd2c917ba7004c3e49d5daf795a2/py_cpuinfo-9.0.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "859625bc251f64e21f077d099d4162689c762b5d6a4c3c97553d56241c9674d5"

[[packages]]
name = "pygments"
version = "2.20.0"

[[packages.wheels]]
name = "pygments-2.20.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/pygments-2.20.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "72b3a2c9c1f6eae60e2023e19d2d706cc0a6e0b2c40cc7fd94b9264a380e7569"

[[packages]]
name = "pytest"
version = "9.1.1"

[[packages.wheels]]
name = "pytest-9.1.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/24/25/1de2678b631f5a49215c6c96fff41ba892b0a34df68d6d80292b1b48aa7f/pytest-9.1.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "37a86b45efb9a47a61a36449063e8e18d0cab3161329fc099eb21783169c4f0c"

[[packages]]
name = "pytest-benchmark"
version = "5.2.3"

[[packages.wheels]]
name = "pytest_benchmark-5.2.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/33/29/e756e715a48959f1c0045342088d7ca9762a2f509b945f362a316e9412b7/pytest_benchmark-5.2.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "bc839726ad20e99aaa0d11a127445457b4219bdb9e80a1afc4b51da7f96b0803"

[[packages]]
name = "pytest-mock"
version = "3.15.1"

[[packages.wheels]]
name = "pytest_mock-3.15.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/5a/cc/06253936f4a7fa2e0f48dfe6d851d9c56df896a9ab09ac019d70b760619c/pytest_mock-3.15.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "0a25e2eb88fe5168d535041d09a4529a188176ae608a6d249ee65abc0949630d"

[[packages]]
name = "pytest-pretty"
version = "1.3.0"

[[packages.wheels]]
name = "pytest_pretty-1.3.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ab/85/2f97a1b65178b0f11c9c77c35417a4cc5b99a80db90dad4734a129844ea5/pytest_pretty-1.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "074b9d5783cef9571494543de07e768a4dda92a3e85118d6c7458c67297159b7"

[[packages]]
name = "pytest-run-parallel"
version = "0.9.1"

[[packages.wheels]]
name = "pytest_run_parallel-0.9.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/19/88/b09e7e1be1847e61f0602fe691cefb3363dc45bb08564568999a23e484c4/pytest_run_parallel-0.9.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "623d1fc7f7a2bec5487addf791f559e7814de5b135c43434e1740fd63eff3c7f"

[[packages]]
name = "python-dateutil"
version = "2.9.0.post0"

[[packages.wheels]]
name = "python_dateutil-2.9.0.post0-py2.py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/python_dateutil-2.9.0.post0-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "e0dad39eec43965d30ef0dbe870617bd5a7ca795c65fda722a7ab2bbd2b747e3"

[[packages]]
name = "pytz"
version = "2026.2"

[[packages.wheels]]
name = "pytz-2026.2-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ec/dd/96da98f892250475bdf2328112d7468abdd4acc7b902b6af23f4ed958ea0/pytz-2026.2-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "04156e608bee23d3792fd45c94ae47fae1036688e75032eea2e3bf0323d1f126"

[[packages]]
name = "referencing"
version = "0.37.0"

[[packages.wheels]]
name = "referencing-0.37.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/referencing-0.37.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "ae7bf99d7fc3f1f3a44a208aa00ad39f1e89037b67a2f699a11887e432e84b0f"

[[packages]]
name = "rich"
version = "15.0.0"

[[packages.wheels]]
name = "rich-15.0.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/82/3b/64d4899d73f91ba49a8c18a8ff3f0ea8f1c1d75481760df8c68ef5235bf5/rich-15.0.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "33bd4ef74232fb73fe9279a257718407f169c09b78a87ad3d296f548e27de0bb"

[[packages]]
name = "rpds-py"
version = "0.30.0"

[[packages.wheels]]
name = "rpds_py-0.30.0-cp314-cp314-pyemscripten_2026_0_wasm32.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/rpds_py-0.30.0-cp314-cp314-pyemscripten_2026_0_wasm32.whl"

[packages.wheels.hashes]
sha256 = "3b419aa82348a3b54e2e0c47d734bb91753175c7f75ec8e0315300728e761ceb"

[[packages]]
name = "six"
version = "1.17.0"

[[packages.wheels]]
name = "six-1.17.0-py2.py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/six-1.17.0-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "c6681057bd87fdec57e811b8e4007bad38deea284052817fa400d542c6423e2d"

[[packages]]
name = "sortedcontainers"
version = "2.4.0"

[[packages.wheels]]
name = "sortedcontainers-2.4.0-py2.py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/sortedcontainers-2.4.0-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "f9fc70329a6a64a0cca46260abb486035cee345ea9e6f63263529bb05ff3c0d7"

[[packages]]
name = "typing-extensions"
version = "4.16.0"

[[packages.wheels]]
name = "typing_extensions-4.16.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/49/d3/b8441a820a491ddfc024b0b0cf0393375b75ea13866d9c66727e54c2fc80/typing_extensions-4.16.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "481caa481374e813c1b176ada14e97f1f67a4539ce9cfeb3f350d78d6370c2e8"

[[packages]]
name = "typing-inspection"
version = "0.4.2"

[[packages.wheels]]
name = "typing_inspection-0.4.2-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.2/full/typing_inspection-0.4.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "b9719c895b2b6123042043573cbd110c8712d508201dcb3126c378a6face49cb"

[[packages]]
name = "tzdata"
version = "2026.2"

[[packages.wheels]]
name = "tzdata-2026.2-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ce/e4/dccd7f47c4b64213ac01ef921a1337ee6e30e8c6466046018326977efd95/tzdata-2026.2-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "bbe9af844f658da81a5f95019480da3a89415801f6cc966806612cc7169bffe7"
