version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7

  - package-ecosystem: cargo
    directory: /pydantic-core/
    schedule:
      interval: monthly
    groups:
      rust-deps:
        patterns:
          - '*'
        exclude-patterns:
          # pyo3 updates will require jiter updates, we'll handle them manually anyway
          - 'pyo3*'
          # strum updates will require speedate updates
          - 'strum'
          - 'strum_macros'
    cooldown:
      default-days: 7
