# Add 'relnotes-fix' label by default
relnotes-fix:
- changed-files:
  - any-glob-to-any-file: '**'

# Add 'relnotes-fix' label to any PR where the head branch name starts with `fix` or has a `fix` section in the name
relnotes-fix:
 - head-branch: ['^fix', 'fix']

relnotes-feature:
 - head-branch: ['^feature', 'feature']

documentation:
 - head-branch: ['^documentation', 'documentation', '^docs', 'docs']

relnotes-change:
  - head-branch: ['^change', 'change']

relnotes-performance:
  - head-branch: ['^performance', 'performance']

relnotes-packaging:
  - head-branch: ['^bump', 'bump', '^version', 'version', '^packaging', 'packaging']
