changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Packaging
      labels:
        - relnotes-packaging
    - title: New Features
      labels:
        - relnotes-feature
    - title: Changes
      labels:
        - relnotes-change
    - title: Performance
      labels:
        - relnotes-performance
    - title: Fixes
      labels:
        - relnotes-fix
