relnotes-fix:
  - head-branch: ['^fix', 'fix']

relnotes-feature:
 - head-branch: ['^feature', 'feature']

documentation:
 - head-branch: ['^documentation', 'documentation', '^docs', 'docs']

documentation:
- changed-files:
  - any-glob-to-any-file: docs/*

relnotes-change:
  - head-branch: ['^change', 'change']

relnotes-performance:
  - head-branch: ['^performance', 'performance']

relnotes-packaging:
  - head-branch: ['^bump', 'bump', '^version', 'version', '^packaging', 'packaging']
