name: Update Pydantic people
description: Update Pydantic contributors in documentation
inputs:
  token:
    description: 'User token for accessing the GitHub API. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: true

    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        python-version: '3.14'
        activate-environment: true
        enable-cache: true

    - name: Install dependencies
      run: uv pip install -r .github/actions/people/requirements.in
      shell: bash

    - name: Update pydantic people
      run: uv run --no-sync .github/actions/people/people.py
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
