name: Update Pydantic people
description: Update Pydantic contributors in documentation
inputs:
  token:
    description: 'User token for accessing the GitHub API. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: true

    - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
      with:
        python-version: '3.14'
        activate-environment: true

    - name: Install dependencies
      run: uv pip install --requirements .github/actions/people/pylock.toml
      shell: bash

    - name: Update pydantic people
      run: uv run --no-sync .github/actions/people/people.py
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
