name: 🐛 Bug
description: Report a bug or unexpected behavior in pydantic
labels: [bug, unconfirmed]

body:
  - type: markdown
    attributes:
      value:  Thank you for contributing to pydantic! ✊

  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: |
        Just a few checks to make sure you need to create a bug report.
        
        _Sorry to sound so draconian 👿; but every second spend replying to issues is time not spent improving pydantic_
      options:
        - label: I have searched GitHub for a duplicate issue and I'm sure this is something new
          required: true
        - label: I have searched Google & StackOverflow for a solution and couldn't find anything
          required: true
        - label: I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
          required: true
        - label: >
            I am confident that the issue is with pydantic 
            (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or
            [mypy](https://mypy.readthedocs.io/en/stable))
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. 🙏
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.

      placeholder: |
        import pydantic

        ...
      render: Python

  - type: textarea
    id: version
    attributes:
      label: Python, Pydantic & OS Version
      description: |
        Which version Python & Pydantic are you using, and which Operating System?
        
        Please run the following command and copy the output below:

        ```bash
        python -c "import pydantic.utils; print(pydantic.utils.version_info())"
        ```

      render: Text
    validations:
      required: true
