blank_issues_enabled: true
contact_links:
  - name: 🤔 Ask a Question
    url: 'https://github.com/pydantic/pydantic/discussions/new?category=question'
    about: Ask a question about how to use pydantic using github discussions
