name: 🚀 Pydantic V2 Feature request
description: 'Suggest a new feature for Pydantic V2 (NOTE: and we only making critical bug fixes to Pydantic V1)'
labels: [feature request]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to pydantic! ✊

  - type: checkboxes
    id: searched
    attributes:
      label: Initial Checks
      description: |
        Just a few checks to make sure you need to create a feature request.

        _Sorry to sound so draconian 👿; but every second spent replying to issues is time not spent improving pydantic 🙇._
      options:
        - label: I have searched Google & GitHub for similar requests and couldn't find anything
          required: true
        - label: I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please give as much detail as possible about the feature you would like to suggest. 🙏

        You might like to add:
        * A demo of how code might look when using the feature
        * Your use case(s) for the feature
        * Why the feature should be added to pydantic (as opposed to another library or just implemented in your code)
    validations:
      required: true

  - type: checkboxes
    id: affected-components
    attributes:
      label: Affected Components
      description: Which of the following parts of pydantic does this feature affect?
      # keep this lis in sync with bug.yml
      options:
        - label: '[Compatibility between releases](https://docs.pydantic.dev/changelog/)'
        - label: '[Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)'
        - label: '[Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`'
        - label: '[JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)'
        - label: '[Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)'
        - label: '[Model Config](https://docs.pydantic.dev/concepts/config/)'
        - label: '[Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type'
        - label: '[Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)'
        - label: '[Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)'
        - label: '[Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode'
        - label: '[Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.'
