name: codspeed

on:
  push:
    branches:
      - main
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

env:
  UV_FROZEN: true
  UV_PYTHON: 3.13

jobs:
  benchmarks:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      # Using this action is still necessary for CodSpeed to work:
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.UV_PYTHON}}

      - name: install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: true

      - name: Install deps
        run: |
          uv sync --group testing-extra
          uv pip uninstall pytest-speed
          uv pip install pytest-benchmark==4.0.0 pytest-codspeed

      - name: Install rust stable
        id: rust-toolchain
        # no release versioning, see https://github.com/dtolnay/rust-toolchain/issues/180
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable
          components: llvm-tools

      - name: Cache rust
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Build PGO wheel
        id: pgo-wheel
        uses: ./.github/actions/build-pgo-wheel
        with:
          interpreter: ${{ env.UV_PYTHON }}
          rust-toolchain: ${{ steps.rust-toolchain.outputs.name }}
        env:
          # make sure profiling information is present
          CARGO_PROFILE_RELEASE_DEBUG: 'line-tables-only'
          CARGO_PROFILE_RELEASE_STRIP: false

      - name: Install PGO wheel
        run: uv pip install ${{ steps.pgo-wheel.outputs.wheel }} --force-reinstall

      - name: Run CodSpeed benchmarks
        uses: CodSpeedHQ/action@1c8ae4843586d3ba879736b7f6b7b0c990757fab # v4.12.1
        with:
          mode: instrumentation
          run: uv run --group=codspeed pytest tests/benchmarks/ --codspeed
