[build]
rustflags = [
  "-A", "incomplete_features",
]

# see https://pyo3.rs/main/building_and_distribution.html#macos
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
  "-A", "incomplete_features",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
  "-A", "incomplete_features",
]

[alias]
rust-bench = "bench --no-default-features --features mimalloc --features auto-initialize"
