name: Build PGO wheel
description: Builds a PGO-optimized wheel
inputs:
  interpreter:
    description: 'Interpreter to build the wheel for'
    required: true
  rust-toolchain:
    description: 'Rust toolchain to use'
    required: true
outputs:
  wheel:
    description: 'Path to the built wheel'
    value: ${{ steps.find_wheel.outputs.path }}
runs:
  using: "composite"
  steps:
    - name: prepare profiling directory
      shell: bash
      # making this ahead of the compile ensures that the local user can write to this
      # directory; the maturin action (on linux) runs in docker so would create as root
      run: mkdir -p ${{ github.workspace }}/profdata

    - name: build initial wheel
      uses: PyO3/maturin-action@v1
      with:
        manylinux: auto
        args: >
          --release
          --out pgo-wheel
          --interpreter ${{ inputs.interpreter }}
        rust-toolchain: ${{ inputs.rust-toolchain }}
        docker-options: -e CI
      env:
        RUSTFLAGS: '-Cprofile-generate=${{ github.workspace }}/profdata'

    - name: detect rust host
      run: echo RUST_HOST=$(rustc -Vv | grep host | cut -d ' ' -f 2) >> "$GITHUB_ENV"
      shell: bash

    - name: generate pgo data
      run: |
        uv sync --group testing-extra
        uv pip install pydantic-core --no-index --no-deps --find-links pgo-wheel --force-reinstall
        uv run pytest tests/benchmarks
        RUST_HOST=$(rustc -Vv | grep host | cut -d ' ' -f 2)
        rustup run ${{ inputs.rust-toolchain }} bash -c 'echo LLVM_PROFDATA=$RUSTUP_HOME/toolchains/$RUSTUP_TOOLCHAIN/lib/rustlib/$RUST_HOST/bin/llvm-profdata >> "$GITHUB_ENV"'
      shell: bash

    - name: merge pgo data
      run: ${{ env.LLVM_PROFDATA }} merge -o ${{ github.workspace }}/merged.profdata ${{ github.workspace }}/profdata
      shell: pwsh # because it handles paths on windows better, and works well enough on unix for this step

    - name: build pgo-optimized wheel
      uses: PyO3/maturin-action@v1
      with:
        manylinux: auto
        args: >
          --release
          --out dist
          --interpreter ${{ inputs.interpreter }}
        rust-toolchain: ${{inputs.rust-toolchain}}
        docker-options: -e CI
      env:
        RUSTFLAGS: '-Cprofile-use=${{ github.workspace }}/merged.profdata'

    - name: find built wheel
      id: find_wheel
      run: echo "path=$(ls dist/*.whl)" | tee -a "$GITHUB_OUTPUT"
      shell: bash
