from __future__ import annotations as _annotations

from dataclasses import dataclass
from datetime import date, datetime, time, timedelta
from decimal import Decimal
from typing import Any, Literal, Mapping

from pydantic_core import CoreSchema, core_schema
from typing_extensions import TypedDict

# TODO: List of missing types
# deque
# typing.Any
# typing.NamedTuple
# collections.namedtuple
# typing.Sequence
# typing.Iterable
# typing.Type
# typing.Pattern
# ipaddress.IPv4Address
# ipaddress.IPv4Interface
# ipaddress.IPv4Network
# ipaddress.IPv6Address
# ipaddress.IPv6Interface
# ipaddress.IPv6Network
# enum.Enum
# enum.IntEnum
# decimal.Decimal
# pathlib.Path
# uuid.UUID
# ByteSize


@dataclass
class Row:
    field_type: type[Any]
    input_type: type[Any]
    mode: Literal['Lax', 'Strict']
    input_format: Literal['Python', 'JSON', 'Python & JSON']
    condition: str | None = None
    valid_examples: list[Any] | None = None
    invalid_examples: list[Any] | None = None
    core_schemas: list[type[CoreSchema]] | None = None


table: list[Row] = [
    Row(
        str,
        str,
        'Strict',
        'Python & JSON',
        core_schemas=[core_schema.StringSchema],
    ),
    Row(
        str,
        bytes,
        'Lax',
        'Python',
        condition='Assumes UTF-8, error on unicode decoding error.',
        valid_examples=[b'this is bytes'],
        invalid_examples=[b'\x81'],
        core_schemas=[core_schema.StringSchema],
    ),
    Row(
        str,
        bytearray,
        'Lax',
        'Python',
        condition='Assumes UTF-8, error on unicode decoding error.',
        valid_examples=[bytearray(b'this is bytearray' * 3)],
        invalid_examples=[bytearray(b'\x81' * 5)],
        core_schemas=[core_schema.StringSchema],
    ),
    Row(
        bytes,
        bytes,
        'Strict',
        'Python',
        core_schemas=[core_schema.BytesSchema],
    ),
    Row(
        bytes,
        str,
        'Strict',
        'JSON',
        valid_examples=['foo'],
        core_schemas=[core_schema.BytesSchema],
    ),
    Row(
        bytes,
        str,
        'Lax',
        'Python',
        valid_examples=['foo'],
        core_schemas=[core_schema.BytesSchema],
    ),
    Row(
        bytes,
        bytearray,
        'Lax',
        'Python',
        valid_examples=[bytearray(b'this is bytearray' * 3)],
        core_schemas=[core_schema.BytesSchema],
    ),
    Row(
        int,
        int,
        'Strict',
        'Python & JSON',
        condition='Max abs value `2^64` - `i64` is used internally, `bool` explicitly forbidden.',
        invalid_examples=[2**64, True, False],
        core_schemas=[core_schema.IntSchema],
    ),
    Row(
        int,
        int,
        'Lax',
        'Python & JSON',
        condition='`i64`. Limits `numbers > (2 ^ 63) - 1` to `(2 ^ 63) - 1`.',
        core_schemas=[core_schema.IntSchema],
    ),
    Row(
        int,
        float,
        'Lax',
        'Python & JSON',
        condition='`i64`, Must be exact int, e.g. `val % 1 == 0`, raises error for `nan`, `inf`.',
        valid_examples=[2.0],
        invalid_examples=[2.1, 2.2250738585072011e308, float('nan'), float('inf')],
        core_schemas=[core_schema.IntSchema],
    ),
    Row(
        int,
        Decimal,
        'Lax',
        'Python',
        condition='`i64`, Must be exact int, e.g. `val % 1 == 0`.',
        valid_examples=[Decimal(2.0)],
        invalid_examples=[Decimal(2.1)],
        core_schemas=[core_schema.IntSchema],
    ),
    Row(
        int,
        bool,
        'Lax',
        'Python & JSON',
        valid_examples=[True, False],
        core_schemas=[core_schema.IntSchema],
    ),
    Row(
        int,
        str,
        'Lax',
        'Python & JSON',
        condition='`i64`, Must be numeric only, e.g. `[0-9]+`.',
        valid_examples=['123'],
        invalid_examples=['test'],
        core_schemas=[core_schema.IntSchema],
    ),
    Row(
        int,
        bytes,
        'Lax',
        'Python',
        condition='`i64`, Must be numeric only, e.g. `[0-9]+`.',
        valid_examples=[b'123'],
        invalid_examples=[b'test'],
        core_schemas=[core_schema.IntSchema],
    ),
    Row(
        float,
        float,
        'Strict',
        'Python & JSON',
        condition='`bool` explicitly forbidden.',
        invalid_examples=[True, False],
        core_schemas=[core_schema.FloatSchema],
    ),
    Row(
        float,
        int,
        'Strict',
        'Python & JSON',
        valid_examples=[123],
        core_schemas=[core_schema.FloatSchema],
    ),
    Row(
        float,
        str,
        'Lax',
        'Python & JSON',
        condition='Must match `[0-9]+(\\.[0-9]+)?`.',
        valid_examples=['3.141'],
        invalid_examples=['test'],
        core_schemas=[core_schema.FloatSchema],
    ),
    Row(
        float,
        bytes,
        'Lax',
        'Python',
        condition='Must match `[0-9]+(\\.[0-9]+)?`.',
        valid_examples=[b'3.141'],
        invalid_examples=[b'test'],
        core_schemas=[core_schema.FloatSchema],
    ),
    Row(
        float,
        Decimal,
        'Lax',
        'Python',
        valid_examples=[Decimal(3.5)],
        core_schemas=[core_schema.FloatSchema],
    ),
    Row(
        float,
        bool,
        'Lax',
        'Python & JSON',
        valid_examples=[True, False],
        core_schemas=[core_schema.FloatSchema],
    ),
    Row(
        bool,
        bool,
        'Strict',
        'Python & JSON',
        valid_examples=[True, False],
        core_schemas=[core_schema.BoolSchema],
    ),
    Row(
        bool,
        int,
        'Lax',
        'Python & JSON',
        condition='Allowed values: `0, 1`.',
        valid_examples=[0, 1],
        invalid_examples=[2, 100],
        core_schemas=[core_schema.BoolSchema],
    ),
    Row(
        bool,
        float,
        'Lax',
        'Python & JSON',
        condition='Allowed values: `0.0, 1.0`.',
        valid_examples=[0.0, 1.0],
        invalid_examples=[2.0, 100.0],
        core_schemas=[core_schema.BoolSchema],
    ),
    Row(
        bool,
        Decimal,
        'Lax',
        'Python',
        condition='Allowed values: `Decimal(0), Decimal(1)`.',
        valid_examples=[Decimal(0), Decimal(1)],
        invalid_examples=[Decimal(2), Decimal(100)],
        core_schemas=[core_schema.BoolSchema],
    ),
    Row(
        bool,
        str,
        'Lax',
        'Python & JSON',
        condition="Allowed values: `'f'`, `'n'`, `'no'`, `'off'`, `'false'`, `'t'`, `'y'`, `'on'`, `'yes'`, `'true'`.",
        valid_examples=['f', 'n', 'no', 'off', 'false', 't', 'y', 'on', 'yes', 'true'],
        invalid_examples=['test'],
        core_schemas=[core_schema.BoolSchema],
    ),
    Row(
        None,
        None,
        'Strict',
        'Python & JSON',
        core_schemas=[core_schema.NoneSchema],
    ),
    Row(
        date,
        date,
        'Strict',
        'Python',
        core_schemas=[core_schema.DateSchema],
    ),
    Row(
        date,
        datetime,
        'Lax',
        'Python',
        condition='Must be exact date, eg. no `H`, `M`, `S`, `f`.',
        valid_examples=[datetime(2017, 5, 5)],
        invalid_examples=[datetime(2017, 5, 5, 10)],
        core_schemas=[core_schema.DateSchema],
    ),
    Row(
        date,
        str,
        'Strict',
        'JSON',
        condition='Format: `YYYY-MM-DD`.',
        valid_examples=['2017-05-05'],
        invalid_examples=['2017-5-5', '2017/05/05'],
        core_schemas=[core_schema.DateSchema],
    ),
    Row(
        date,
        str,
        'Lax',
        'Python',
        condition='Format: `YYYY-MM-DD`.',
        valid_examples=['2017-05-05'],
        invalid_examples=['2017-5-5', '2017/05/05'],
        core_schemas=[core_schema.DateSchema],
    ),
    Row(
        date,
        bytes,
        'Lax',
        'Python',
        condition='Format: `YYYY-MM-DD` (UTF-8).',
        valid_examples=[b'2017-05-05'],
        invalid_examples=[b'2017-5-5', b'2017/05/05'],
        core_schemas=[core_schema.DateSchema],
    ),
    Row(
        date,
        int,
        'Lax',
        'Python & JSON',
        condition=(
            'Interpreted as seconds or ms from epoch. '
            'See [speedate](https://docs.rs/speedate/latest/speedate/). Must be exact date.'
        ),
        valid_examples=[1493942400000, 1493942400],
        invalid_examples=[1493942401000],
        core_schemas=[core_schema.DateSchema],
    ),
    Row(
        date,
        float,
        'Lax',
        'Python & JSON',
        condition=(
            'Interpreted as seconds or ms from epoch. '
            'See [speedate](https://docs.rs/speedate/latest/speedate/). Must be exact date.'
        ),
        valid_examples=[1493942400000.0, 1493942400.0],
        invalid_examples=[1493942401000.0],
        core_schemas=[core_schema.DateSchema],
    ),
    Row(
        date,
        Decimal,
        'Lax',
        'Python',
        condition=(
            'Interpreted as seconds or ms from epoch. '
            'See [speedate](https://docs.rs/speedate/latest/speedate/). Must be exact date.'
        ),
        valid_examples=[Decimal(1493942400000), Decimal(1493942400)],
        invalid_examples=[Decimal(1493942401000)],
        core_schemas=[core_schema.DateSchema],
    ),
    Row(
        datetime,
        datetime,
        'Strict',
        'Python',
        core_schemas=[core_schema.DatetimeSchema],
    ),
    Row(
        datetime,
        date,
        'Lax',
        'Python',
        valid_examples=[date(2017, 5, 5)],
        core_schemas=[core_schema.DatetimeSchema],
    ),
    Row(
        datetime,
        str,
        'Strict',
        'JSON',
        condition='Format: `YYYY-MM-DDTHH:MM:SS.f`. See [speedate](https://docs.rs/speedate/latest/speedate/).',
        valid_examples=['2017-05-05 10:10:10', '2017-05-05T10:10:10.0002', '2017-05-05 10:10:10+00:00'],
        invalid_examples=['2017-5-5T10:10:10'],
        core_schemas=[core_schema.DatetimeSchema],
    ),
    Row(
        datetime,
        str,
        'Lax',
        'Python',
        condition='Format: `YYYY-MM-DDTHH:MM:SS.f`. See [speedate](https://docs.rs/speedate/latest/speedate/).',
        valid_examples=['2017-05-05 10:10:10', '2017-05-05T10:10:10.0002', '2017-05-05 10:10:10+00:00'],
        invalid_examples=['2017-5-5T10:10:10'],
        core_schemas=[core_schema.DatetimeSchema],
    ),
    Row(
        datetime,
        bytes,
        'Lax',
        'Python',
        condition=(
            'Format: `YYYY-MM-DDTHH:MM:SS.f`. See [speedate](https://docs.rs/speedate/latest/speedate/), (UTF-8).'
        ),
        valid_examples=[b'2017-05-05 10:10:10', b'2017-05-05T10:10:10.0002', b'2017-05-05 10:10:10+00:00'],
        invalid_examples=[b'2017-5-5T10:10:10'],
        core_schemas=[core_schema.DatetimeSchema],
    ),
    Row(
        datetime,
        int,
        'Lax',
        'Python & JSON',
        condition='Interpreted as seconds or ms from epoch, see [speedate](https://docs.rs/speedate/latest/speedate/).',
        valid_examples=[1493979010000, 1493979010],
        core_schemas=[core_schema.DatetimeSchema],
    ),
    Row(
        datetime,
        float,
        'Lax',
        'Python & JSON',
        condition='Interpreted as seconds or ms from epoch, see [speedate](https://docs.rs/speedate/latest/speedate/).',
        valid_examples=[1493979010000.0, 1493979010.0],
        core_schemas=[core_schema.DatetimeSchema],
    ),
    Row(
        datetime,
        Decimal,
        'Lax',
        'Python',
        condition='Interpreted as seconds or ms from epoch, see [speedate](https://docs.rs/speedate/latest/speedate/).',
        valid_examples=[Decimal(1493979010000), Decimal(1493979010)],
        core_schemas=[core_schema.DatetimeSchema],
    ),
    Row(
        time,
        time,
        'Strict',
        'Python',
        core_schemas=[core_schema.TimeSchema],
    ),
    Row(
        time,
        str,
        'Strict',
        'JSON',
        condition='Format: `HH:MM:SS.FFFFFF`. See [speedate](https://docs.rs/speedate/latest/speedate/).',
        valid_examples=['10:10:10.0002'],
        invalid_examples=['1:1:1'],
        core_schemas=[core_schema.TimeSchema],
    ),
    Row(
        time,
        str,
        'Lax',
        'Python',
        condition='Format: `HH:MM:SS.FFFFFF`. See [speedate](https://docs.rs/speedate/latest/speedate/).',
        valid_examples=['10:10:10.0002'],
        invalid_examples=['1:1:1'],
        core_schemas=[core_schema.TimeSchema],
    ),
    Row(
        time,
        bytes,
        'Lax',
        'Python',
        condition='Format: `HH:MM:SS.FFFFFF`. See [speedate](https://docs.rs/speedate/latest/speedate/).',
        valid_examples=[b'10:10:10.0002'],
        invalid_examples=[b'1:1:1'],
        core_schemas=[core_schema.TimeSchema],
    ),
    Row(
        time,
        int,
        'Lax',
        'Python & JSON',
        condition='Interpreted as seconds, range `0 - 86399`.',
        valid_examples=[3720],
        invalid_examples=[-1, 86400],
        core_schemas=[core_schema.TimeSchema],
    ),
    Row(
        time,
        float,
        'Lax',
        'Python & JSON',
        condition='Interpreted as seconds, range `0 - 86399.9*`.',
        valid_examples=[3720.0002],
        invalid_examples=[-1.0, 86400.0],
        core_schemas=[core_schema.TimeSchema],
    ),
    Row(
        time,
        Decimal,
        'Lax',
        'Python',
        condition='Interpreted as seconds, range `0 - 86399.9*`.',
        valid_examples=[Decimal(3720.0002)],
        invalid_examples=[Decimal(-1), Decimal(86400)],
        core_schemas=[core_schema.TimeSchema],
    ),
    Row(
        timedelta,
        timedelta,
        'Strict',
        'Python',
        core_schemas=[core_schema.TimedeltaSchema],
    ),
    Row(
        timedelta,
        str,
        'Strict',
        'JSON',
        condition='Format: `ISO8601`. See [speedate](https://docs.rs/speedate/latest/speedate/).',
        valid_examples=['1 days 10:10', '1 d 10:10'],
        invalid_examples=['1 10:10'],
        core_schemas=[core_schema.TimedeltaSchema],
    ),
    Row(
        timedelta,
        str,
        'Lax',
        'Python',
        condition='Format: `ISO8601`. See [speedate](https://docs.rs/speedate/latest/speedate/).',
        valid_examples=['1 days 10:10', '1 d 10:10'],
        invalid_examples=['1 10:10'],
        core_schemas=[core_schema.TimedeltaSchema],
    ),
    Row(
        timedelta,
        bytes,
        'Lax',
        'Python',
        condition='Format: `ISO8601`. See [speedate](https://docs.rs/speedate/latest/speedate/), (UTF-8).',
        valid_examples=[b'1 days 10:10', b'1 d 10:10'],
        invalid_examples=[b'1 10:10'],
        core_schemas=[core_schema.TimedeltaSchema],
    ),
    Row(
        timedelta,
        int,
        'Lax',
        'Python & JSON',
        condition='Interpreted as seconds.',
        valid_examples=[123_000],
        core_schemas=[core_schema.TimedeltaSchema],
    ),
    Row(
        timedelta,
        float,
        'Lax',
        'Python & JSON',
        condition='Interpreted as seconds.',
        valid_examples=[123_000.0002],
        core_schemas=[core_schema.TimedeltaSchema],
    ),
    Row(
        timedelta,
        Decimal,
        'Lax',
        'Python',
        condition='Interpreted as seconds.',
        valid_examples=[Decimal(123_000.0002)],
        core_schemas=[core_schema.TimedeltaSchema],
    ),
    Row(
        dict,
        dict,
        'Strict',
        'Python',
        core_schemas=[core_schema.DictSchema],
    ),
    Row(
        dict,
        'Object',
        'Strict',
        'JSON',
        valid_examples=['{"v": {"1": 1, "2": 2}}'],
        core_schemas=[core_schema.DictSchema],
    ),
    Row(
        dict,
        Mapping,
        'Lax',
        'Python',
        condition='Must implement the mapping interface and have an `items()` method.',
        valid_examples=[],
        core_schemas=[core_schema.DictSchema],
    ),
    Row(
        TypedDict,
        dict,
        'Strict',
        'Python',
        core_schemas=[core_schema.TypedDictSchema],
    ),
    Row(
        TypedDict,
        'Object',
        'Strict',
        'JSON',
        core_schemas=[core_schema.TypedDictSchema],
    ),
    Row(
        TypedDict,
        Any,
        'Strict',
        'Python',
        core_schemas=[core_schema.TypedDictSchema],
    ),
    Row(
        TypedDict,
        Mapping,
        'Lax',
        'Python',
        condition='Must implement the mapping interface and have an `items()` method.',
        valid_examples=[],
        core_schemas=[core_schema.TypedDictSchema],
    ),
    Row(
        list,
        list,
        'Strict',
        'Python',
        core_schemas=[core_schema.ListSchema],
    ),
    Row(
        list,
        'Array',
        'Strict',
        'JSON',
        core_schemas=[core_schema.ListSchema],
    ),
    Row(
        list,
        tuple,
        'Lax',
        'Python',
        core_schemas=[core_schema.ListSchema],
    ),
    Row(
        list,
        'dict_keys',
        'Lax',
        'Python',
        core_schemas=[core_schema.ListSchema],
    ),
    Row(
        list,
        'dict_values',
        'Lax',
        'Python',
        core_schemas=[core_schema.ListSchema],
    ),
    Row(
        tuple,
        tuple,
        'Strict',
        'Python',
        core_schemas=[core_schema.TuplePositionalSchema, core_schema.TupleVariableSchema],
    ),
    Row(
        tuple,
        'Array',
        'Strict',
        'JSON',
        core_schemas=[core_schema.TuplePositionalSchema, core_schema.TupleVariableSchema],
    ),
    Row(
        tuple,
        list,
        'Lax',
        'Python',
        core_schemas=[core_schema.TuplePositionalSchema, core_schema.TupleVariableSchema],
    ),
    Row(
        tuple,
        'dict_keys',
        'Lax',
        'Python',
        core_schemas=[core_schema.TuplePositionalSchema, core_schema.TupleVariableSchema],
    ),
    Row(
        tuple,
        'dict_values',
        'Lax',
        'Python',
        core_schemas=[core_schema.TuplePositionalSchema, core_schema.TupleVariableSchema],
    ),
    Row(
        set,
        set,
        'Strict',
        'Python',
        core_schemas=[core_schema.SetSchema],
    ),
    Row(
        set,
        'Array',
        'Strict',
        'JSON',
        core_schemas=[core_schema.SetSchema],
    ),
    Row(
        set,
        list,
        'Lax',
        'Python',
        core_schemas=[core_schema.SetSchema],
    ),
    Row(
        set,
        tuple,
        'Lax',
        'Python',
        core_schemas=[core_schema.SetSchema],
    ),
    Row(
        set,
        frozenset,
        'Lax',
        'Python',
        core_schemas=[core_schema.SetSchema],
    ),
    Row(
        set,
        'dict_keys',
        'Lax',
        'Python',
        core_schemas=[core_schema.SetSchema],
    ),
    Row(
        set,
        'dict_values',
        'Lax',
        'Python',
        core_schemas=[core_schema.SetSchema],
    ),
    Row(
        frozenset,
        frozenset,
        'Strict',
        'Python',
        core_schemas=[core_schema.FrozenSetSchema],
    ),
    Row(
        frozenset,
        'Array',
        'Strict',
        'JSON',
        core_schemas=[core_schema.FrozenSetSchema],
    ),
    Row(
        frozenset,
        list,
        'Lax',
        'Python',
        core_schemas=[core_schema.FrozenSetSchema],
    ),
    Row(
        frozenset,
        tuple,
        'Lax',
        'Python',
        core_schemas=[core_schema.FrozenSetSchema],
    ),
    Row(
        frozenset,
        set,
        'Lax',
        'Python',
        core_schemas=[core_schema.FrozenSetSchema],
    ),
    Row(
        frozenset,
        'dict_keys',
        'Lax',
        'Python',
        core_schemas=[core_schema.FrozenSetSchema],
    ),
    Row(
        frozenset,
        'dict_values',
        'Lax',
        'Python',
        core_schemas=[core_schema.FrozenSetSchema],
    ),
    Row(
        isinstance,
        Any,
        'Strict',
        'Python',
        condition='`isinstance()` check returns `True`.',
        core_schemas=[core_schema.IsInstanceSchema],
    ),
    Row(
        isinstance,
        '-',
        'Strict',
        'JSON',
        condition='Never valid.',
        core_schemas=[core_schema.IsInstanceSchema],
    ),
    Row(
        callable,
        Any,
        'Strict',
        'Python',
        condition='`callable()` check returns `True`.',
        core_schemas=[core_schema.CallableSchema],
    ),
    Row(
        callable,
        '',
        'Strict',
        'JSON',
        condition='Never valid.',
        core_schemas=[core_schema.CallableSchema],
    ),
]
