name: Cherry Pick

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  cherry_pick:
    runs-on: ubuntu-latest

    name: Cherry pick into 1.10.X-fixes

    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'cherry-pick-v1')

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cherry pick into 1.10.X-fixes
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
        with:
          branch: 1.10.X-fixes
          labels: from-cherry-pick
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '[cherry-pick] {old_title}'
          body: 'Cherry picking #{old_pull_request_id} onto this branch'
