name: release notes

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  auto-labeler:
    name: auto-labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
    - uses: actions/labeler@v5
  check:
    needs: auto-labeler
    name: has one relnotes label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python release/check_relnotes.py
