name: release notes

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  check:
    name: has one relnotes label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python release/check_relnotes.py
