name: Pydantic people update

on:
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  pydantic-people:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/people
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
